### ISSUE TITLE
Bad Request when using `Elmas.authorize`

### ISSUE THREAD

**Issue by marckohlbrugge** [exactonline/exactonline-api-ruby-client#39] opened 2016-10-15 17:58 UTC
I'm trying to authorize Elmas using this method described in the Readme:

```ruby
require "elmas"

Elmas.configure do |config|
  config.access_token = Elmas.authorize(ENV['EXACT_USER_NAME'], ENV['EXACT_PASSWORD']).access_token
end
```

Which results in the following error message:

```
JSON::ParserError: 784: unexpected token at 'Bad Request'
	from /Users/marc/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /Users/marc/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /Users/marc/.rvm/gems/ruby-2.3.0/gems/elmas-2.3.1/lib/elmas/oauth.rb:110:in `body'
	from /Users/marc/.rvm/gems/ruby-2.3.0/gems/elmas-2.3.1/lib/elmas/response.rb:22:in `parsed'
	from /Users/marc/.rvm/gems/ruby-2.3.0/gems/elmas-2.3.1/lib/elmas/response.rb:42:in `error_message'
	from /Users/marc/.rvm/gems/ruby-2.3.0/gems/elmas-2.3.1/lib/elmas/response.rb:46:in `log_error'
	from /Users/marc/.rvm/gems/ruby-2.3.0/gems/elmas-2.3.1/lib/elmas/response.rb:65:in `raise_and_log_error'
	from /Users/marc/.rvm/gems/ruby-2.3.0/gems/elmas-2.3.1/lib/elmas/response.rb:10:in `initialize'
	from /Users/marc/.rvm/gems/ruby-2.3.0/gems/elmas-2.3.1/lib/elmas/oauth.rb:18:in `new'
	from /Users/marc/.rvm/gems/ruby-2.3.0/gems/elmas-2.3.1/lib/elmas/oauth.rb:18:in `authorize'
	from /Users/marc/.rvm/gems/ruby-2.3.0/gems/elmas-2.3.1/lib/elmas.rb:57:in `method_missing'
	from (irb):43
	from /Users/marc/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
```

The error log doesn't provide any additional information.

Any recommendations on debugging this? Is there a way to see the actual requests Elmas made?

I double checked ENV variables and also tried entering the login information directly, but I keep running into this same problem.

**Comment by Bramjetten** [comment] 2016-10-17 08:25
I just spent an hour or two debugging this, and I think it's caused by the redirect_uri. The gem uses the https://www.getpostman.com/oauth2/callback by default. If you set up your app to use this as the redirect_uri it should work.

**Comment by Marthyn** [comment] 2016-10-18 07:27
@Bramjetten You are right, i will add this to the readme. Since our implementation is application to application and the redirect uri does not matter we didn't realize this. @marckohlbrugge Sorry for the inconvenience.

**Comment by Marthyn** [comment] 2016-10-18 07:55
It is in the readme now, i'll close this issue. Please open it again if you still have problems @marckohlbrugge

**Closed by Marthyn** 2016-10-18 07:55 UTC
